In [8]:
src = '../data/quickdraw-raw'

In [6]:
import numpy as np
from PIL import Image
import math
import glob 

In [12]:
appleSrc = src + '/full_numpy_bitmap_apple.npy'
appleNp = np.load(appleSrc)

In [13]:
appleNp.shape

(144722, 784)

In [24]:
anApple = appleNp[ np.random.randint(0, appleNp.shape[0]) ].reshape(28, 28)
im = Image.fromarray(anApple)
im.show()

In [5]:
path = '/home/User/Documents/filesfdgsfdg sdfgsfdg.txt'
from os.path import dirname, basename, isfile

In [6]:
basename(path)[:-4]

'filesfdgsfdg sdfgsfdg'

In [12]:
glob.glob(src + '/*.npy')

['../data/quickdraw-raw\\full_numpy_bitmap_aircraft carrier.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_airplane.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_angel.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_ant.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_apple.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_banana.npy',
 '../data/quickdraw-raw\\full_numpy_bitmap_The Eiffel Tower.npy']

In [14]:
'full_numpy_bitmap_The Eiffel Tower'.replace("full_numpy_bitmap_", "").replace(" ", "_")

'The_Eiffel_Tower'

In [24]:
basename('data/quickdraw-raw\\full_numpy_bitmap_airplane.npy'.replace('\\','\/'))[:-4]

'full_numpy_bitmap_airplane'

In [22]:
'data/quickdraw-raw\\full_numpy_bitmap_airplane.npy'.replace('\\','/')

'data/quickdraw-raw/full_numpy_bitmap_airplane.npy'

In [1]:
import datetime

In [2]:
today = datetime.datetime.now()

In [3]:
today.strftime("%b")

'Nov'

In [10]:
dic = {'z': 1, 'b': 2, 'c': 3}

In [13]:
np.random.choice(list(dic.keys()), 10)

array(['b', 'b', 'z', 'z', 'c', 'z', 'b', 'b', 'z', 'c'], dtype='<U1')

In [11]:
list(dic.keys())

['z', 'b', 'c']

In [12]:
list(dic.keys())

['z', 'b', 'c']

In [31]:
choices = np.random.randint(0, 5, 100)
choices

array([3, 3, 4, 4, 3, 3, 0, 1, 2, 2, 3, 4, 1, 1, 4, 4, 3, 4, 0, 1, 1, 4,
       0, 4, 1, 1, 3, 4, 1, 2, 2, 2, 2, 3, 1, 0, 1, 0, 3, 4, 4, 3, 4, 2,
       2, 0, 3, 4, 0, 4, 1, 2, 4, 3, 0, 1, 3, 4, 0, 2, 1, 2, 4, 1, 0, 2,
       2, 1, 1, 4, 3, 3, 1, 1, 1, 1, 3, 4, 1, 3, 2, 3, 3, 3, 0, 2, 1, 4,
       1, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 4])

In [30]:
counts = np.unique(choices, return_counts=True)
counts

(array([0, 1, 2, 3, 4]), array([15, 24, 20, 20, 21], dtype=int64))

In [23]:
counts[1][3]

18

In [24]:
784/28

28.0

In [32]:
np.eye(5)[0] / 100

array([0.01, 0.  , 0.  , 0.  , 0.  ])